$(".btn-1848").click(function(){
    $(this).css('background-image','url(img/painel01/bt01_hover.png)');
});
$(".btn-1872").click(function(){
    $(this).css('background-image','url(img/painel01/bt02_hover.png)');
});
$(".btn-1925").click(function(){
    $(this).css('background-image','url(img/painel01/bt03_hover.png)');
});
$(".btn-1934").click(function(){
    $(this).css('background-image','url(img/painel01/bt04_hover.png)');
});
$(".btn-1943").click(function(){
    $(this).css('background-image','url(img/painel01/bt05_hover.png)');
});
$(".btn-1988").click(function(){
    $(this).css('background-image','url(img/painel01/bt06_hover.png)');
});


$(".btn-1848_mobile").click(function(){
    $(this).css('background-image','url(img/painel01/bt01_hover.png)');
});
$(".btn-1872_mobile").click(function(){
    $(this).css('background-image','url(img/painel01/bt02_hover.png)');
});
$(".btn-1925_mobile").click(function(){
    $(this).css('background-image','url(img/painel01/bt03_hover.png)');
});
$(".btn-1934_mobile").click(function(){
    $(this).css('background-image','url(img/painel01/bt04_hover.png)');
});
$(".btn-1943_mobile").click(function(){
    $(this).css('background-image','url(img/painel01/bt05_hover.png)');
});
$(".btn-1988_mobile").click(function(){
    $(this).css('background-image','url(img/painel01/bt06_hover.png)');
});


$(".btn-aquisitivo").click(function(){
    $(".check-aquisitivo").css('display','block');
});
$(".btn-concessivo").click(function(){
    $(".check-concessivo").css('display','block');
});
$(".btn-parcelamento").click(function(){
    $(".check-parcelamento").css('display','block');
});


$(".alternativa-a").click(function(){
    $(".resposta-a").css('display','block');
    $(".resposta-b").css('display','none');
    $(".resposta-c").css('display','none');
    $(".resposta-d").css('display','none');
});
$(".alternativa-b").click(function(){
    $(".resposta-a").css('display','none');
    $(".resposta-b").css('display','block');
    $(".resposta-c").css('display','none');
    $(".resposta-d").css('display','none');
});
$(".alternativa-c").click(function(){
    $(".resposta-a").css('display','none');
    $(".resposta-b").css('display','none');
    $(".resposta-c").css('display','block');
    $(".resposta-d").css('display','none');
});
$(".alternativa-d").click(function(){
    $(".resposta-a").css('display','none');
    $(".resposta-b").css('display','none');
    $(".resposta-c").css('display','none');
    $(".resposta-d").css('display','block');
});