$(".btn-vale").click(function(){
    $(".check-vale").css('display','block');
});
$(".btn-assistencia").click(function(){
    $(".check-assistencia").css('display','block');
});
$(".btn-odontologico").click(function(){
    $(".check-odontologico").css('display','block');
});
$(".btn-bolsa").click(function(){
    $(".check-bolsa").css('display','block');
});
$(".btn-creche").click(function(){
    $(".check-creche").css('display','block');
});
$(".btn-cultura").click(function(){
    $(".check-cultura").css('display','block');
});
$(".btn-previdencia").click(function(){
    $(".check-previdencia").css('display','block');
});
$(".btn-plr").click(function(){
    $(".check-plr").css('display','block');
});

$("#btn-premios").click(function(){
    $(this).css('background-image','url(img/painel02/bt01_hover.png)');
});
$("#btn-reforma_salarial").click(function(){
    $(this).css('background-image','url(img/painel02/bt02_hover.png)');
});
$("#btn-saude").click(function(){
    $(this).css('background-image','url(img/painel02/bt03_hover.png)');
});
$("#btn-viagem").click(function(){
    $(this).css('background-image','url(img/painel02/bt04_hover.png)');
});
$("#btn-contribuicoes").click(function(){
    $(this).css('background-image','url(img/painel02/bt05_hover.png)');
});